//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Prof
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc_Prof()
        {
            this.Detalle_Revision_Protocolo = new HashSet<Detalle_Revision_Protocolo>();
        }
    
        public int IdDoc_Prof { get; set; }
        public Nullable<int> IdDoc { get; set; }
        public Nullable<int> IdProf { get; set; }
        public Nullable<int> RolProf { get; set; }
        public Nullable<System.DateTime> FechaAsignada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Revision_Protocolo> Detalle_Revision_Protocolo { get; set; }
        public virtual Documento Documento { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
