//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_Doc
    {
        public int IdEst_Doc { get; set; }
        public Nullable<int> Carnet { get; set; }
        public Nullable<int> IdDoc { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
